project_id = "gqbhilftduwxjszznnzy"

[functions.stripe-webhook]
verify_jwt = false

[functions.cleanup-inactive-users]
verify_jwt = false

[functions.csp-report]
verify_jwt = false

[functions.auth-start]
verify_jwt = false

[functions.sign-tax-return]
verify_jwt = false

[functions.ocr-extract]
verify_jwt = false

[functions.ocr-model]
verify_jwt = false
