
import { FormData } from './types';

export const defaultFormData: FormData = {
  contactInfo: {
    adressnummer: '',
    firstName: '',
    lastName: '',
    email: '',
    phone: '',
    address: '',
    postalCode: '',
    city: '',
    kanton: '' as any,
    birthDate: '',
    religion: '' as any,
    maritalStatus: '' as any,
    firefighterService: undefined as any,
    hasChildren: undefined as any,
    children: [],
    hadDifferentAddressEnd: undefined as any,
    endYearAddress: '',
    endYearAdressnummer: '',
    endYearPostalCode: '',
    endYearCity: '',
    endYearKanton: '' as any,
    spouseFirstName: '',
    spouseLastName: '',
    spouseReligion: '' as any
  },
  contact: {
    adressnummer: '',
    firstName: '',
    lastName: '',
    email: '',
    phone: '',
    address: '',
    postalCode: '',
    city: '',
    kanton: '' as any,
    birthDate: '',
    religion: '' as any,
    maritalStatus: '' as any,
    firefighterService: undefined as any,
    hasChildren: undefined as any,
    children: [],
    hadDifferentAddressEnd: undefined as any,
    endYearAddress: '',
    endYearAdressnummer: '',
    endYearPostalCode: '',
    endYearCity: '',
    endYearKanton: '' as any,
    spouseFirstName: '',
    spouseLastName: '',
    spouseReligion: '' as any
  },
  income: {
    hasSalary: undefined as any,
    hasRental: undefined as any,
    hasDividends: undefined as any,
    hasFreelance: undefined as any,
    hasPension: undefined as any,
    hasGiftInheritance: undefined as any,
    hasPensionPayout: undefined as any,
    hasOtherIncome: undefined as any,
    otherIncomeString: '',
    employers: [],
    employmentIncome: 0,
    selfEmploymentIncome: 0,
    rentalIncome: 0,
    capitalIncome: 0,
    pensionIncome: 0,
    otherIncome: 0,
    rentalIncomes: [],
    dividends: [],
    freelanceIncome: []
  },
  assets: {
    hasVehicle: undefined as any,
    hasProperty: undefined as any,
    hasMortgage: undefined as any,
    hasDebt: undefined as any,
    hasDepositAccount: undefined as any,
    hasSecuritiesAccount: undefined as any,
    hasCrypto: undefined as any,
    hasOtherAssets: undefined as any,
    otherAssetsString: '',
    vehicles: [],
    properties: [],
    debts: [],
    bankAccounts: 0,
    stocks: 0,
    realEstate: 0,
    cryptocurrency: 0,
    otherAssets: 0
  },
  deductions: {
    hasPillar3a: undefined as any,
    hasBVGPurchase: undefined as any,
    hasEducationExpenses: undefined as any,
    hasDonations: undefined as any,
    hasPropertyMaintenance: undefined as any,
    hasOtherDeductions: undefined as any,
    hasSupportedPersons: undefined as any,
    hasMaintenancePayments: undefined as any,
    hasWorkRelatedExpenses: undefined as any,
    hasChildcare: undefined as any,
    otherDeductions: '',
    supportedPersons: [],
    maintenancePayments: [],
    healthInsurance: 0,
    charitableDonations: 0,
    retirementContributions: 0,
    medicalExpenses: 0,
    educationExpenses: 0,
    childcareExpenses: 0
  }
};
