// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqbhilftduwxjszznnzy.supabase.co";

// SECURITY NOTE: This is a Supabase ANON key (public key), NOT a secret JWT.
// It is DESIGNED to be publicly exposed and protected by Row Level Security (RLS).
// Security scanners may flag this as "JWT leak" - this is a FALSE POSITIVE.
// See SECURITY.md for detailed explanation of why ANON keys are safe to expose.
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxYmhpbGZ0ZHV3eGpzenpubnp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNjAxMjgsImV4cCI6MjA2MDgzNjEyOH0.u2qQOA3rIET_HevF92lrDpABK5xctFBuUqhcQUsStZs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});